src/objects/Broker__c.object
<CustomObject>
    <description>Archived system function</description>
    <fields>
        <fullName>Listing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipName>Brokers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Leasing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Leasing</label>
        <referenceTo>Project_Leasing__c</referenceTo>
        <relationshipName>Brokers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sale__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sale</label>
        <referenceTo>Sale__c</referenceTo>
        <relationshipName>Brokers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>system.broker</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Broker&apos;s ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>system.brokers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Commission__c.object
<CustomObject>
    <fields>
        <fullName>Listing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Do not adjust. The system will update automatically.</inlineHelpText>
        <label>Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipLabel>Commissions</relationshipLabel>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sale__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Do not adjust. The system will update automatically.</inlineHelpText>
        <label>Comp</label>
        <referenceTo>Sale__c</referenceTo>
        <relationshipLabel>Commissions</relationshipLabel>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active Pipeline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Pipeline</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Commission</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Commission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Escrow__c.object
<CustomObject>
    <fields>
        <fullName>Landlord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Landlord</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Projects (Landlord)</relationshipLabel>
        <relationshipName>Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Listing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Escrows</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Escrows</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Space__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Space</label>
        <referenceTo>Spaces__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Escrow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>System_Commis__c</fullName>
        <defaultValue>false</defaultValue>
        <label>System_Commis</label>
        <type>Checkbox</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Lease</fullName>
        <active>true</active>
        <label>Pending Lease</label>
    </recordTypes>
    <recordTypes>
        <fullName>Sale</fullName>
        <active>true</active>
        <label>Pending Sale</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Listing__c.object
<CustomObject>
    <fields>
        <fullName>Owner_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Listings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipName>Listings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pre-Marketing Preparation</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>On-Market</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Off-Market</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Contract</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>System_Commis__c</fullName>
        <defaultValue>false</defaultValue>
        <label>System_Commis</label>
        <type>Checkbox</type>
    </fields>
    <label>Listing</label>
    <nameField>
        <label>Listing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project_Leasing__c.object
<CustomObject>
    <description>Archived system function</description>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Project_Leasing</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipName>Project_Leasing</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>On Market</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Off Market</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>system.project leasing</label>
    <nameField>
        <label>Project Leasing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>system.project leasings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Square_Footage__c</fullName>
        <label>Square Footage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sale__c.object
<CustomObject>
    <fields>
        <fullName>Landlord_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Landlord (Contact)</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Comps (Landlord)</relationshipLabel>
        <relationshipName>Comps2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Landlord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Landlord</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Comps (Landlord)</relationshipLabel>
        <relationshipName>Comps1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Listing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created as requirement of the third project.</description>
        <label>Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipName>Sales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property_Leases__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property Leased</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Lease Comps</relationshipLabel>
        <relationshipName>Comps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property Sold</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Sale Comps</relationshipLabel>
        <relationshipName>Sales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Space__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Space</label>
        <referenceTo>Spaces__c</referenceTo>
        <relationshipLabel>Lease History</relationshipLabel>
        <relationshipName>Comps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Square_Footage__c</fullName>
        <label>Square Footage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Suite_Floor__c</fullName>
        <label>Suite/Floor #</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_Commis__c</fullName>
        <defaultValue>false</defaultValue>
        <label>System_Commis</label>
        <type>Checkbox</type>
    </fields>
    <label>Comp</label>
    <nameField>
        <label>Comp Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comps</pluralLabel>
    <recordTypes>
        <fullName>Lease</fullName>
        <active>true</active>
        <label>Lease</label>
    </recordTypes>
    <recordTypes>
        <fullName>Sale</fullName>
        <active>true</active>
        <label>Sale</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Spaces__c.object
<CustomObject>
    <fields>
        <fullName>Landlord_Representation_Assignment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Landlord Representation Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Spaces</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Leasing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Leasing</label>
        <referenceTo>Project_Leasing__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Spaces</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Spaces</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Square_Footage__c</fullName>
        <label>Available Square Footage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Suite_Floor__c</fullName>
        <label>Suite/Floor #</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Space</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Spaces Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sale__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Comp</label>
        <referenceTo>Sale__c</referenceTo>
        <relationshipLabel>Parties to the Transaction</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Party to the Transaction</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parties to the Transaction</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SpaceProjectController.cls
/**
 * Shrew Designs
 * creates a Project with the Lease record type.
 * copy the Property, Project Leasing, and Update the Record Name with “Suite/Floor [Suite_Floor] 
 * Pending Lease” and update the Status to [Pending].
 *
 *@author: Chetan Garg
 */ 
public  class SpaceProjectController {
	// Properties (Default get/set)
    public boolean hasSaved {get;set;}
    public string spaceId {get;set;}
    
    // Construcgor
    public SpaceProjectController(ApexPages.StandardController stdCon){
        spaceId = stdCon.getId();
    }
    
    // Methods
    public Pagereference initPage(){
    	if(apexPAges.currentPage().getParameters().get('p') == 'comp'){
    		return createComp();
    	}else if(apexPAges.currentPage().getParameters().get('p') == 'escrow'){
    		return createProject();
    	}
    	return null;
    }
    
     public Pagereference createComp(){
        Pagereference pg = null;
        Savepoint sp = Database.setSavepoint();
        try{
            RecordType leaseRecordtype = [Select id from RecordType where DeveloperName = 'Lease' and sobjectType='Sale__c'];
             
            Spaces__c space = [Select Project_Leasing__r.Name, Id,Landlord_Representation_Assignment__r.Owner_Contact__c, Suite_Floor__c,Landlord_Representation_Assignment__c, 
                                Property__c,Property__r.Name, Project_Leasing__c,Property__r.Square_Footage__c
                                ,Landlord_Representation_Assignment__r.Owner_Contact__r.AccountID,Square_Footage__c
                                ,Project_Leasing__r.Property__r.Square_Footage__c, Property__r.OwnerId From Spaces__c where id=:spaceId];
                                
            // Create and insert a comp                    
            Sale__c sale = new Sale__c();
                sale.Name = space.Property__r.Name + '- Suite/Floor #'+ space.Suite_Floor__c;
                sale.System_Commis__c = true;
                sale.Listing__c = space.Landlord_Representation_Assignment__c;
                sale.Space__c = space.id;
                sale.RecordTypeId = leaseRecordType.Id;
               //sale.Property__c = space.Property__c;
                sale.Property_Leases__c = space.Property__c;
                sale.Suite_Floor__c = space.Suite_Floor__c;
                sale.Square_Footage__c = space.Square_Footage__c;
                
                sale.Landlord__c = space.Landlord_Representation_Assignment__r.Owner_Contact__r.AccountId;
                sale.Landlord_Contact__c = space.Landlord_Representation_Assignment__r.Owner_Contact__c;
                
        	upsert sale;
            space.Status__c = 'Leased';
            update space;
            
            //List of parties to the transaction to be update in the database
            Transaction__c[] partiesToUpdate = new Transaction__c[]{};
            if(sale.Landlord_Contact__c != null){
                Transaction__c party = new Transaction__c();
                party.Contact__c = sale.Landlord_Contact__c;
                party.Sale__c = sale.Id;
                party.Role__c = 'Lessor';
                party.Transcation_Company__c = sale.Landlord__c;
                partiesToUpdate.add(party); 
            }else if (sale.Landlord__c != null){
                Transaction__c party = new Transaction__c();
                party.Contact__c = sale.Landlord_Contact__c;
                party.Sale__c = sale.Id;
                party.Role__c = 'Lessor';
                party.Transcation_Company__c = sale.Landlord__c;
                partiesToUpdate.add(party); 
            }
            insert partiesToUpdate;
            
            // Create and Insert a commission  
	        Commission__c comm = new Commission__c();
		        comm.broker__c = space.Property__r.OwnerId;
		        comm.Sale__c = sale.id;
	        insert comm;
	        
            pg = new Pagereference('/'+sale.id);
            
        }catch(Exception ex){
            Database.rollback(sp);
            Apexpages.addMessages(ex);
        }
        return pg;
    }
    
    public Pagereference createProject(){
        Pagereference pg = null;
        Savepoint sp = Database.setSavepoint();
        try{
            RecordType leaseRecordtype = [Select id from RecordType where developerName = 'Lease' and sobjectType='Escrow__c'];
            Spaces__c space = [Select Id,Landlord_Representation_Assignment__r.Owner_Contact__c, Suite_Floor__c,Landlord_Representation_Assignment__c, 
                                Property__c,Property__r.Name, Project_Leasing__c, Property__r.OwnerId From Spaces__c where id=:spaceId];
            // Create the project
            Escrow__c project = new Escrow__c();
            
            	project.Name =  space.Property__r.Name + '- Suite/Floor #'+ space.Suite_Floor__c + ' Lease (' +  datetime.now().format('MM/dd/yyyy') +')';
            	project.Space__C = space.id;
            	project.Property__c = space.Property__c;
            	project.landlord__c = space.Landlord_Representation_Assignment__r.Owner_Contact__c;
	            project.Status__c = 'Pending';
	            project.RecordTypeId = leaseRecordType.Id;
	            project.System_Commis__c = true;
	            project.Listing__c = space.Landlord_Representation_Assignment__c;
	            
            insert project;
            space.Status__c = 'Pending';
            update space;
            // Create and Insert the commission
            Commission__c comm = new Commission__c();
                comm.broker__c = space.Property__r.OwnerId;
                comm.Escrow__c = project.id;
            insert comm;
            
            //List of parties to the transaction to be update in the database
            Transaction__c[] partiesToUpdate = new Transaction__c[]{};
            if(project.landlord__c != null){
                Transaction__c party = new Transaction__c();
                party.Contact__c = project.landlord__c;
                party.Escrow__c = project.Id;
                party.Role__c = 'Lessor';
                party.Transcation_Company__c = project.landlord_Company__c;
                partiesToUpdate.add(party); 
            }else if (project.landlord_Company__c != null){
                Transaction__c party = new Transaction__c();
                party.Contact__c = project.landlord__c;
                party.Escrow__c = project.Id;
                party.Role__c = 'Lessor';
                party.Transcation_Company__c = project.landlord_Company__c;
                partiesToUpdate.add(party); 
            }
            insert partiesToUpdate;
            
            // Create redirect PageReference
            pg = new Pagereference('/'+project.id);
        }catch(Exception ex){
            Database.rollback(sp);
            Apexpages.addMessages(ex);
        }
        return pg;
    }
    
    /*
    Commented code:
    
                
            /*
            //List of parties to the transaction to be update in the database
            Transaction__c[] partiesToUpdate = new Transaction__c[]{};
            
            for(Sale__c sale : saleList) {
                                    
                if(parties.size() > 0) {
                    for(Transaction__c party : parties) {
                        party.Sale__c = sale.Id;
                    }
                    partiesToUpdate.addAll(parties);
                    
                    
                }
                if(project.RecordType.Name == 'Pending Sale'){
                    if(space.Landlord_Representation_Assignment__r.Owner_Contact__c != null ){
                        Transaction__c party = new Transaction__c();
                        party.Contact__c = project.Listing__r.Owner_Contact__c;
                        party.Sale__c = sale.Id;
                        party.Role__c = 'Lessor';
                        partiesToUpdate.add(party); 
                    }
                    
                    if(project.landlord__c != null){
                        Transaction__c party = new Transaction__c();
                        party.Contact__c = project.landlord__c;
                        party.Sale__c = sale.Id;
                        party.Role__c = 'Lessee';
                        partiesToUpdate.add(party); 
                    }
                }
            }
            
            
            
            //insert parties;
            
            //update the parties to the database
            //upsert (partiesToUpdate);
            
            //Escrow__c es = new Escrow__c(id = project.id, Status__c = 'Closed');
            //project.Status__c = 'Closed';
           // update  es;
           
            */
           

}