src/objects/Broker__c.object
<CustomObject>
    <description>Archived system function</description>
    <label>system.broker</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Broker&apos;s ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>system.brokers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Commission__c.object
<CustomObject>
    <fields>
        <fullName>Broker_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>External Agent</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Commissions</relationshipLabel>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Broker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Internal Agent</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Commission</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Commission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Commission_Payment__c.object
<CustomObject>
    <fields>
        <fullName>Broker_Id__c</fullName>
        <formula>IF( Commission__r.RecordType.DeveloperName = &quot;External&quot;,
 Commission__r.Broker_Contact__c ,
 Commission__r.Broker__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Broker Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Broker__c</fullName>
        <formula>HYPERLINK(
&apos;/&apos; +  Broker_Id__c ,
IF( Commission__r.RecordType.DeveloperName = &quot;External&quot;, 
 Commission__r.Broker_Contact__r.FirstName + &apos; &apos; + Commission__r.Broker_Contact__r.LastName,
 Commission__r.Broker__r.FirstName + &apos; &apos; +  Commission__r.Broker__r.LastName ),
&quot;_parent&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Broker</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commission_Calculation_Details__c</fullName>
        <label>Commission Calculation Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Commission__c</fullName>
        <label>Commission</label>
        <referenceTo>Commission__c</referenceTo>
        <relationshipName>Commission_Payables</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_Processed__c</fullName>
        <inlineHelpText>The date that was used when the net commissions were calculated. This is used to know what period the commission applies to.</inlineHelpText>
        <label>Date Processed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gross_Commission_Formula__c</fullName>
        <formula>Commission__r.Agent_Gross_Commission__c *  Invoice__r.Percent_Due__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The agent gross commission times the percent due from the invoice.</inlineHelpText>
        <label>Gross Commission</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Commission Payments</relationshipLabel>
        <relationshipName>Commission_Payables</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Net_Commission__c</fullName>
        <label>Net Commission</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Commission Payment</label>
    <nameField>
        <displayFormat>CP-{00000}</displayFormat>
        <label>Payable ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commission Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{000}{DD}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/InvoiceTriggerHelper.cls
public with sharing class InvoiceTriggerHelper {
	
	public Invoice__c[] ProcessPaidInvoices(Invoice__c[] PaidInvoices){
		// Get a set of Ids
		Set<Id> invoiceIds = new set<id>();
		for(Invoice__c invoice : PaidInvoices){
			invoiceIds.add(invoice.Id);
		}
		
		// Get the Commission Payables
		// To-do: Bulkify this since there could be many payments per invoice
		Commission_Payment__c[] payments = [Select c.Commission__r.RecordType.DeveloperName, c.Invoice__c, c.Broker_Id__c, c.Commission__r.Broker__c, c.Commission__r.Broker_Contact__c, c.Gross_Commission_Formula__c, c.Net_Commission__c, c.Commission_Calculation_Details__c From Commission_Payment__c c where c.Invoice__c in :InvoiceIds and c.Date_Processed__c = null];
		 
		CommissionPaymentCalculator.calculateCommissions(payments);
		update payments;
		
		// Return Invoices
		return PaidInvoices;
	}
}