src/objects/Broker__c.object
<CustomObject>
    <description>Archived system function</description>
    <fields>
        <fullName>Escrow__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Escrow</label>
        <referenceTo>Escrow__c</referenceTo>
        <relationshipName>Brokers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Listing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipName>Brokers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sale__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sale</label>
        <referenceTo>Sale__c</referenceTo>
        <relationshipName>Brokers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>system.broker</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Broker&apos;s ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>system.brokers</pluralLabel>
    <recordTypes>
        <fullName>External_Broker</fullName>
        <active>false</active>
        <label>External Broker</label>
    </recordTypes>
    <recordTypes>
        <fullName>Internal_Broker</fullName>
        <active>true</active>
        <label>Internal Broker</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Commission__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Date__c</fullName>
        <label>Activity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Agent_Gross_Commission__c</fullName>
        <formula>IF( RecordType.DeveloperName = &quot;Internal_Broker&quot; &amp;&amp; NOT(ISBLANK(Sale__c)),
(Formula_Gross_Commission__c - Sale__r.Total_Holdbacks__c) * Agent_Percentage__c,
Formula_Gross_Commission__c * Agent_Percentage__c)</formula>
        <label>Agent Gross Commission</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Agent_Percentage__c</fullName>
        <defaultValue>1.00</defaultValue>
        <label>Agent Percentage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Broker_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>External Agent</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Commissions</relationshipLabel>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Broker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Internal Agent</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Escrow__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Do not adjust. The system will update automatically.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Escrow__c</referenceTo>
        <relationshipLabel>Commissions</relationshipLabel>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Listing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Do not adjust. The system will update automatically.</inlineHelpText>
        <label>Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipLabel>Commissions</relationshipLabel>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Do not adjust. The system will update automatically.</inlineHelpText>
        <label>Proposal</label>
        <referenceTo>Proposal__c</referenceTo>
        <relationshipLabel>Commissions</relationshipLabel>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sale__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Do not adjust. The system will update automatically.</inlineHelpText>
        <label>Comp</label>
        <referenceTo>Sale__c</referenceTo>
        <relationshipLabel>Commissions</relationshipLabel>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Commission</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Commission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <recordTypes>
        <fullName>External_Broker</fullName>
        <active>true</active>
        <description>Is this commission for an external broker?</description>
        <label>External Broker</label>
    </recordTypes>
    <recordTypes>
        <fullName>Internal_Broker</fullName>
        <active>true</active>
        <description>Is this commission for an internal broker?</description>
        <label>Internal Broker</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Escrow__c.object
<CustomObject>
    <fields>
        <fullName>Escrow__c</fullName>
        <label>Commission ($)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Listing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Escrows</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for third project requirements.</description>
        <label>Proposal</label>
        <referenceTo>Proposal__c</referenceTo>
        <relationshipName>Escrows</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <recordTypes>
        <fullName>Sale</fullName>
        <active>true</active>
        <label>Pending Sale</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Listing__c.object
<CustomObject>
    <fields>
        <fullName>Commission_Input__c</fullName>
        <inlineHelpText>Please estimate for pipeline tracking purposes</inlineHelpText>
        <label>Commission ($)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Commission__c</fullName>
        <label>Commission (%)</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Proposal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Added for the third project requirement.</description>
        <label>Proposal</label>
        <referenceTo>Proposal__c</referenceTo>
        <relationshipName>Listings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Listing</label>
    <nameField>
        <label>Listing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Proposal__c.object
<CustomObject>
    <fields>
        <fullName>Commission__c</fullName>
        <inlineHelpText>Please estimate for pipeline tracking purposes</inlineHelpText>
        <label>Commission ($)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Proposal</label>
    <nameField>
        <label>Proposal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sale__c.object
<CustomObject>
    <fields>
        <fullName>Commission__c</fullName>
        <label>Commission ($)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Escrow__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Escrow</label>
        <referenceTo>Escrow__c</referenceTo>
        <relationshipName>Sales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Listing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created as requirement of the third project.</description>
        <label>Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipName>Sales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created as requirement for third project.</description>
        <label>Proposal</label>
        <referenceTo>Proposal__c</referenceTo>
        <relationshipName>Sales</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Comp</label>
    <nameField>
        <label>Comp Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comps</pluralLabel>
    <recordTypes>
        <fullName>Sale</fullName>
        <active>true</active>
        <label>Sale</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EditCommissionsController.cls
/* This controls the functionality on the Edit Commissions Page.
The page is accessible from the commissions related list on the Proposals, Listings, Projects, or Comps */

public with sharing class EditCommissionsController {
     
    public list<Commission__c> ExternalCommissions {get;set;}
    public list<Commission__c> InternalCommissions {get;set;}
    Commission__c[] CommissionsToDelete = new Commission__c[]{};
    private map<string,Id> CommissionRecordTypes;
    
    public EditCommissionsController(ApexPages.StandardController stdCon){
        getParentObject();
        CommissionRecordTypes = RecordTypeManager.GetRecordTypeIdsByDeveloperName(Commission__c.SObjectType);
        if(!CommissionRecordTypes.containsKey('External_Broker')&&!CommissionRecordTypes.containsKey('Internal_Broker')){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL,'Error: You do not have access to the correct record types for the Commissions object. Please contact Apto support.'));
        }
        ExternalCommissions = [select Agent_Percentage__c, Activity_Date__c, Broker_Contact__c, Agent_Gross_Commission__c from Commission__c 
            where (Proposal__c = :parentobject.Id or Listing__c = :parentobject.Id or Escrow__c = :parentobject.Id or Sale__c = :parentobject.Id) and RecordType.DeveloperName = 'External_Broker'];
        InternalCommissions = [select Agent_Percentage__c, Activity_Date__c, Broker__c, Agent_Gross_Commission__c from Commission__c 
            where (Proposal__c = :parentobject.Id or Listing__c = :parentobject.Id or Escrow__c = :parentobject.Id or Sale__c = :parentobject.Id) and RecordType.DeveloperName = 'Internal_Broker'];
    }
    
    public EditCommissionsController(){
        getParentObject();
        CommissionRecordTypes = RecordTypeManager.GetRecordTypeIdsByDeveloperName(Commission__c.SObjectType);
        if(!CommissionRecordTypes.containsKey('External_Broker')&&!CommissionRecordTypes.containsKey('Internal_Broker')){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL,'Error: You do not have access to the correct record types for the Commissions object. Please contact Apto support.'));
        }
        ExternalCommissions = [select Agent_Percentage__c, Activity_Date__c, Broker_Contact__c, Agent_Gross_Commission__c from Commission__c 
            where (Proposal__c = :parentobject.Id or Listing__c = :parentobject.Id or Escrow__c = :parentobject.Id or Sale__c = :parentobject.Id) and RecordType.DeveloperName = 'External_Broker'];
        InternalCommissions = [select Agent_Percentage__c, Activity_Date__c, Broker__c, Agent_Gross_Commission__c from Commission__c 
            where (Proposal__c = :parentobject.Id or Listing__c = :parentobject.Id or Escrow__c = :parentobject.Id or Sale__c = :parentobject.Id) and RecordType.DeveloperName = 'Internal_Broker'];
    }
    
    public class ParentRecord{
        public string Name {get; set;}
        public string ObjectType {get; set;}
        public string ObjectLabel {get; set;}
        public Id Id {get; set;}
        public double Commissions {get; set;}
    }
    
    public decimal getTotalpercent(){
        Commission__c[] commissions = new Commission__c[]{};
        commissions.addAll(ExternalCommissions);
        commissions.addAll(InternalCommissions);
        decimal totalPercent = 0;
        for(Commission__c c : commissions){
            totalPercent += c.Agent_Percentage__c/100;
        }
        return totalPercent;
    }
    
    private ParentRecord parentobject;
    
    public ParentRecord getParentObject(){
        if(parentobject==null){
            parentobject = new ParentRecord();
            parentobject.Id = (Id) ApexPages.CurrentPage().getparameters().get('Id');
            if(parentobject.Id == null){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL,'System Error: No ID Specified. Please go back and try again. If the problem continues, contact Apto Support'));
            }else{
                parentobject.ObjectType = parentobject.Id.GetSObjectType().getDescribe().getName();
                parentobject.ObjectLabel = parentobject.Id.GetSObjectType().getDescribe().getLabel();
            }
            if(parentobject.ObjectType<>null){
                if(parentobject.ObjectType.containsIgnoreCase('Proposal__c')){
                    Proposal__c proposal = [Select p.Name, p.Id, p.Commission__c From Proposal__c p where p.id = :parentobject.Id];
                    parentObject.Name = proposal.Name;
                    parentObject.Commissions = proposal.Commission__c;
                }else if(parentobject.ObjectType.containsIgnoreCase('Listing__c')){
                    Listing__c listing = [Select l.Name, l.Id, l.Commission_Input__c From Listing__c l where l.id = :parentobject.Id];
                    parentObject.Name = listing.Name;
                    parentObject.Commissions = listing.Commission_Input__c;
                }else if(parentobject.ObjectType.containsIgnoreCase('Escrow__c')){
                    Escrow__c escrow = [Select p.Name, p.Id, p.Escrow__c From Escrow__c p where id = :parentobject.Id];
                    parentObject.Name = escrow.Name;
                    parentObject.Commissions = escrow.Escrow__c;
                }else if(parentobject.ObjectType.containsIgnoreCase('Sale__c')){
                    Sale__c sale = [Select p.Name, p.Id, p.Commission__c From Sale__c p where id = :parentobject.Id];
                    parentObject.Name = sale.Name;
                    parentObject.Commissions = sale.Commission__c;
                }
            }
        }
        return parentobject;
    }
    
    public pageReference save(){
        if(getTotalPercent()<>1){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL,'The Agent Percentages must add to 100%'));
            return null;
        }
        Commission__c[] CommissionsToInsert = new Commission__c[]{};
        Commission__c[] CommissionsToUpdate = new Commission__c[]{};
        for(Commission__c c : ExternalCommissions){
            if(c.Id==null) CommissionstoInsert.add(c);
            else CommissionstoUpdate.add(c);
        }
        for(Commission__c c : InternalCommissions){
            if(c.Id==null) CommissionstoInsert.add(c);
            else CommissionstoUpdate.add(c);
        }
        try{
            if(CommissionsToDelete.size()>0) delete CommissionsToDelete;
            if(CommissionsToUpdate.size()>0) update CommissionsToUpdate;
            if(CommissionsToInsert.size()>0) insert CommissionsToInsert;
        }catch(System.DMLexception e){
            for (Integer i = 0; i < e.getNumDml(); i++) { 
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL,'Error updating commissions: '+e.getDmlMessage(i))); 
            }
            
        }
        if(ApexPages.hasMessages()){
            return null;
        }else if(ApexPages.currentPage().getUrl().containsignorecase('bookdealwizard')){
            return null;
        }else{
            return new PageReference('/'+parentobject.Id);
        }
    }
    
    public pageReference cancel(){
        return new PageReference('/'+parentobject.Id);
    }
    
    public pageReference addExternalCommission(){
        Decimal totalPercent = 1 - getTotalPercent();
        if(totalPercent<0) totalPercent = 0;
        Commission__c newCommission = new Commission__c(RecordTypeId = CommissionRecordTypes.get('External_Broker'), Agent_Percentage__c = totalPercent*100);
        newCommission = addParentId(newCommission,parentObject);
        ExternalCommissions.add(newCommission);
        return null;
    }
    
    public pageReference addInternalCommission(){
        Decimal totalPercent = 1 - getTotalPercent();
        if(totalPercent<0) totalPercent = 0;
        Commission__c newCommission = new Commission__c(RecordTypeId = CommissionRecordTypes.get('Internal_Broker'), Agent_Percentage__c = totalPercent*100);
        newCommission = addParentId(newCommission,parentObject);
        InternalCommissions.add(newCommission);
        return null;
    }
    
    private Commission__c addParentId(Commission__c com, parentRecord parent){
        if(parent.ObjectType.containsIgnoreCase('Proposal__c')){
            com.Proposal__c = parent.Id;
        }else if(parent.ObjectType.containsIgnoreCase('Listing__c')){
            com.Listing__c = parent.Id;
        }else if(parent.ObjectType.containsIgnoreCase('Escrow__c')){
            com.Escrow__c = parent.Id;
        }else if(parent.ObjectType.containsIgnoreCase('Sale__c')){
            com.Sale__c = parent.Id;
        }
        return com;
    }
    
    public Integer numberOfRowToRemove {get; set;}
    public pageReference removeExternalCommission(){
    	system.debug('ExternalCommissions-------------'+ExternalCommissions);
        if(ExternalCommissions.get(numberofRowToRemove).Id<>null) CommissionsToDelete.add(ExternalCommissions.get(numberofRowToRemove));
        ExternalCommissions.remove(numberOfRowToRemove);
        return null;
    }
    
    public pageReference removeInternalCommission(){
    	system.debug('InternalCommissions-------------'+InternalCommissions);
        if(InternalCommissions.get(numberofRowToRemove).Id<>null) CommissionsToDelete.add(InternalCommissions.get(numberofRowToRemove));
        InternalCommissions.remove(numberOfRowToRemove);
        return null;
    }
    
}