src/objects/Broker__c.object
<CustomObject>
    <description>Archived system function</description>
    <label>system.broker</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Broker&apos;s ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>system.brokers</pluralLabel>
    <recordTypes>
        <fullName>External_Broker</fullName>
        <active>false</active>
        <label>External Broker</label>
    </recordTypes>
    <recordTypes>
        <fullName>Internal_Broker</fullName>
        <active>true</active>
        <label>Internal Broker</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Commission__c.object
<CustomObject>
    <fields>
        <fullName>Broker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Internal Agent</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Commission</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Commission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <recordTypes>
        <fullName>External_Broker</fullName>
        <active>true</active>
        <description>Is this commission for an external broker?</description>
        <label>External Broker</label>
    </recordTypes>
    <recordTypes>
        <fullName>Internal_Broker</fullName>
        <active>true</active>
        <description>Is this commission for an internal broker?</description>
        <label>Internal Broker</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Commission_Payment__c.object
<CustomObject>
    <fields>
        <fullName>Agent_Split__c</fullName>
        <label>Agent Split</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Broker_Id__c</fullName>
        <formula>IF( Commission__r.RecordType.DeveloperName = &quot;External&quot;,
 Commission__r.Broker_Contact__c ,
 Commission__r.Broker__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Broker Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Broker__c</fullName>
        <formula>HYPERLINK(
&apos;/&apos; +  Broker_Id__c ,
IF( Commission__r.RecordType.DeveloperName = &quot;External&quot;, 
 Commission__r.Broker_Contact__r.FirstName + &apos; &apos; + Commission__r.Broker_Contact__r.LastName,
 Commission__r.Broker__r.FirstName + &apos; &apos; +  Commission__r.Broker__r.LastName ),
&quot;_parent&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Broker</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commission_Calculation_Details__c</fullName>
        <label>Commission Calculation Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Commission_Record_Type__c</fullName>
        <formula>Commission__r.RecordType.DeveloperName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Commission Record Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Commission__c</fullName>
        <label>Commission</label>
        <referenceTo>Commission__c</referenceTo>
        <relationshipName>Commission_Payables</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_Processed__c</fullName>
        <inlineHelpText>The date that was used when the net commissions were calculated. This is used to know what period the commission applies to.</inlineHelpText>
        <label>Date Processed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gross_Commission_Formula__c</fullName>
        <formula>Commission__r.Agent_Gross_Commission__c *  Invoice__r.Percent_Due__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The agent gross commission times the percent due from the invoice.</inlineHelpText>
        <label>Gross Commission</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Net_Commission__c</fullName>
        <label>Net Commission</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Commission Payment</label>
    <nameField>
        <displayFormat>CP-{00000}</displayFormat>
        <label>Payable ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commission Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Commission_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Calculate_Splits__c</fullName>
        <inlineHelpText>Do you calculate splits based on when the comp is booked or when the payment is received?</inlineHelpText>
        <label>Calculate Splits</label>
        <picklist>
            <picklistValues>
                <fullName>Booked</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Commission Plan</label>
    <nameField>
        <label>Commission Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commission Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Commission_Plan_Member__c.object
<CustomObject>
    <fields>
        <fullName>Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agent</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Commission_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commission_Plan__c</fullName>
        <label>Commission Plan</label>
        <referenceTo>Commission_Plan__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Commission Plan Member</label>
    <nameField>
        <displayFormat>CPM-{00000}</displayFormat>
        <label>Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commission Plan Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Commission_Plan_Split__c.object
<CustomObject>
    <fields>
        <fullName>Agent_Split__c</fullName>
        <label>Agent Split</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Commission_Plan__c</fullName>
        <label>Commission Plan</label>
        <referenceTo>Commission_Plan__c</referenceTo>
        <relationshipLabel>Splits</relationshipLabel>
        <relationshipName>Splits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Gross_Commission_From__c</fullName>
        <label>Gross Commission From</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gross_Commission_To__c</fullName>
        <label>Gross Commission To</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Commission Plan Split</label>
    <nameField>
        <displayFormat>Split-{0000}</displayFormat>
        <label>Split Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commission Plan Splits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CommissionPaymentCalculator.cls
public with sharing class CommissionPaymentCalculator {
	
	public static void checkNewPaymentsAndCalculateCommissions(Commission_Payment__c[] newPayments){
		set<Id> AgentIds = getAgentIdsFromPayments(newPayments);
		Map<Id,Commission_Plan__c> AgentPlans = getAgentPlans(AgentIds);
		Commission_Payment__c[] PaymentsToProcess = new Commission_Payment__c[]{};
		if(AgentPlans.size()>0){
			for(Commission_Payment__c payment : newPayments){
				if(payment.Commission_Record_Type__c == 'Internal_Broker'){
					Commission_Plan__c plan = AgentPlans.get((Id) payment.Broker_Id__c);
					if(plan == null){
						payment.addError('No Commission plan for this broker. Please add them to a commission plan.');
					}else{
						if(plan.Calculate_Splits__c == 'Booked'){
							PaymentsToProcess.add(payment);
						}
					}
				}
			}
		}
		System.debug(PaymentsToProcess);
		if(PaymentsToProcess.size()>0){
			calculateCommissions(PaymentsToProcess);
		}
		
	}
	
	public static Commission_Payment__c[] calculateCommissions(Commission_Payment__c[] payments){
		set<Id> AgentIds = getAgentIdsFromPayments(payments);
		Map<Id,Commission_Plan__c> AgentPlans = getAgentPlans(AgentIds);
		return calculateCommissions(payments,AgentPlans);
	}
	
	public static Commission_Payment__c[] calculateCommissions(Commission_Payment__c[] payments, Map<Id,Commission_Plan__c> AgentPlans){
		// Get previous agent totals
		map<id,decimal> AgentTotals = getAgentTotals(AgentPlans.keySet());
		
		// Calculate Net Commissions
		for(Commission_Payment__c payment : payments){
			payment.Commission_Calculation_Details__c = null;
			if(payment.Commission__r.RecordType.DeveloperName == 'External_Broker'){
				payment.Net_Commission__c = payment.Gross_Commission_Formula__c;
				payment.Commission_Calculation_Details__c = String.ValueOf(date.today().format())+' External Broker - no splits calculated';
			}else{
				Commission_Plan__c agentPlan = AgentPlans.get(payment.Broker_Id__c);
				Decimal AgentTotal = AgentTotals.get(payment.Broker_Id__c);
				payment.Net_Commission__c = 0;
				payment.Commission_Calculation_Details__c = String.ValueOf(date.today().format())+' Recalculated Net Commissions based on Plan: '+AgentPlan.Name;
				payment.Commission_Calculation_Details__c += '\n\rPrevious Gross Commissions: '+AgentTotal;
				for(Commission_Plan_Split__c split : agentPlan.Splits__r){
					Decimal AmountForSplit = 0;
					if(split.Gross_Commission_To__c == null){
						// Special calculation for the last split
						AmountForSplit = AgentTotal+payment.Gross_Commission_Formula__c - Math.Max(AgentTotal,split.Gross_Commission_From__c);
					}else{
						System.Debug('Agent Total: '+AgentTotal);
						System.Debug('payment: '+payment);
						System.Debug('split: '+split);   
						AmountForSplit = Math.Min(AgentTotal+payment.Gross_Commission_Formula__c,split.Gross_Commission_To__c) - Math.Max(AgentTotal,split.Gross_Commission_From__c);
					}
					if(AmountForSplit>0){
						payment.Commission_Calculation_Details__c += '\n\r'+AmountForSplit+' x '+split.Agent_Split__c/100 + ' = '+AmountForSplit*split.Agent_Split__c/100;
						payment.Net_Commission__c += AmountForSplit*split.Agent_Split__c/100;
					}
					
				}
				payment.Commission_Calculation_Details__c += '\n\rTotal Commission: '+payment.Net_Commission__c;
				
			}
			payment.Date_Processed__c = date.today();
		}
		
		return payments;
	}
	
	
	
	private static Map<id,Commission_Plan__c> getAgentPlans(Set<id> AgentIds){
		
		// Get the Commission Plans for the Agents
		Map<Id,Commission_Plan__c> AgentPlans = new Map<id,Commission_Plan__c>();
		for(Commission_Plan_Member__c member : [select Commission_Plan__c, Agent__c from Commission_Plan_Member__c where Agent__c in :AgentIds]){
			AgentPlans.put(member.Agent__c,new Commission_Plan__c(id = member.Commission_Plan__c));
		}
		
		// Get a map of commission plans
		Map<id,Commission_Plan__c> PlanMap = new Map<id,Commission_Plan__c>([Select c.Id, c.Calculate_Splits__c, c.Name, (Select Gross_Commission_From__c, Gross_Commission_To__c, Agent_Split__c From Splits__r order by Gross_Commission_From__c asc) From Commission_Plan__c c where Id in :AgentPlans.Values()]);
		
		// Update the Agent Plan map with the full details of the paln
		for(Id AgentID : AgentPlans.keySet()){
			AgentPlans.put(AgentId,PlanMap.get(AgentPlans.get(AgentId).Id));
		}
		return AgentPlans;
	}
		
	
	private static Map<Id,Decimal> getAgentTotals(set<id> AgentIds){ 
		// Get previous totals for the Agents
		Map<id,decimal> AgentTotals = new Map<Id,decimal>();
		AggregateResult[] groupedResults
		  = [SELECT Commission__r.Broker__c cb, SUM(Gross_Commission_Formula__c)
		      FROM Commission_Payment__c
		      where Date_Processed__c = THIS_FISCAL_YEAR and Commission__r.Broker__c in :AgentIds
		      GROUP BY Commission__r.Broker__c];
		for (AggregateResult ar : groupedResults)  {
			AgentTotals.put((Id) ar.get('cb'), (decimal) ar.get('expr0'));
		}
		
		for(Id AgentID : AgentIds){
			if(!AgentTotals.containsKey(AgentId)) AgentTotals.put(AgentId,0);
		}
		return AgentTotals;
	}
	
	private static set<id> getAgentIdsFromPayments(Commission_Payment__c[] payments){
		Set<Id> AgentIds = new Set<id>();
		for(Commission_Payment__c payment : payments){
			if(payment.Broker_Id__c <> null){
				AgentIds.add(payment.Broker_Id__c);
			}
		}
		return AgentIds;
	}
}