src/objects/Broker__c.object
<CustomObject>
    <description>Archived system function</description>
    <fields>
        <fullName>Listing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipName>Brokers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Brokers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>system.broker</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Broker&apos;s ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>system.brokers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Listing__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <formula>Property__r.City__c</formula>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interest_Rate__c</fullName>
        <label>Interest Rate</label>
        <precision>5</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Loan_Performance__c</fullName>
        <label>Loan Performance</label>
        <picklist>
            <picklistValues>
                <fullName>Non-Performing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub-Performing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Loan_Type__c</fullName>
        <label>Loan Type</label>
        <picklist>
            <picklistValues>
                <fullName>All Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assumption</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proposed New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Seller</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <label>Project Type</label>
        <picklist>
            <picklistValues>
                <fullName>Investment Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan Sale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leasing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Listing Engine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Banking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financing / Equity / Debt</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipName>Listings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>TEXT(Property__r.State__c)</formula>
        <label>State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>rcm1id__c</fullName>
        <description>External ID from rcm1 system</description>
        <externalId>true</externalId>
        <label>rcm1id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Listing</label>
    <nameField>
        <label>Listing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <label>Building Class</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ORANGE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OKALOOSA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OKLAHOMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alamance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albemarle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alexander</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alleghany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archdale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ashe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bath</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beaufort</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bertie</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bladen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brunswick</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buncombe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burke</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bute</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cabarrus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caldwell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Camden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carteret</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caswell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Catawba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chatham</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cherokee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cherokee Reservation (Qualla Boundary)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chowan</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Land_Acres__c</fullName>
        <label>Land (Acres)</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Occupancy__c</fullName>
        <label>Occupancy (%)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Primary_Use__c</fullName>
        <label>Primary Use</label>
        <picklist>
            <picklistValues>
                <fullName>Airplane Hangar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Airport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Salvage Facility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cement or Gravel Plant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chemical or Oil Refinery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contractor Storage Yard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distribution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flex- Data Hosting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flex-Showroom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ind- Data Hosting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ind-Showroom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industrial Live &amp; Work Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Landfill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Light Distribution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Light Manufacturing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loft &amp; Creative Space</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lumberyard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Office &amp; Residential</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Office- Data Hosting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Office Live &amp; Work Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Office with street-level Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R&amp;D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Railroad Yard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refrigeration &amp; Cold Storage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self-Storage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Property_Address__c</fullName>
        <label>Property Address</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Rooms__c</fullName>
        <label>Room Count</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Square_Footage__c</fullName>
        <label>Square Footage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Type__c</fullName>
        <description>This field is only used when pulling/pushing data from/into McLabs</description>
        <label>Unit Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Units__c</fullName>
        <label>Units</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ListingAdapter.cls
public with sharing class ListingAdapter {

    private final String S_NAMESPACE = McLabsConstants.RCM1_S_NAMESPACE;
    private final String B_NAMESPACE = McLabsConstants.RCM1_B_NAMESPACE;
    private final String DIFFGR_NAMESPACE = McLabsConstants.RCM1_DIFFGR_NAMESPACE;
    

    private static final Map<String, String> CONTENT_TYPES = new Map<String, String>{
        'png' => 'image/png',
        'jpg' => 'image/jpeg',
        'jpeg' => 'image/jpeg',
        'gif'  => 'image/gif',
        'tiff' => 'image/tiff',
        
        'pdf'  => 'application/pdf',
        'txt'  => 'text/plain',
        'html' => 'text/html',
        'doc'  => 'application/msword',
        'docx' => 'application/msword2007',
        'xls'  => 'application/msexcel',
        'xlsx' => 'application/msexcel2007',
        'zip'  => 'compressed/zip',
        'rar'  => 'compressed/rar'
    };
    /*
        FILE_EXT_MAP.put("image/png", "png");
        FILE_EXT_MAP.put("image/jpeg", "jpg");
        FILE_EXT_MAP.put("image/jpeg", "jpeg");
        FILE_EXT_MAP.put("image/pjpeg", "jpg");
        FILE_EXT_MAP.put("image/gif", "gif");
        FILE_EXT_MAP.put("image/tiff", "tiff");
        FILE_EXT_MAP.put("application/pdf", "pdf");
        FILE_EXT_MAP.put("video/mpeg", "mpeg");
        FILE_EXT_MAP.put("video/mp4", "mp4");
        FILE_EXT_MAP.put("video/quicktime", "mov");
        FILE_EXT_MAP.put("video/x-ms-wmv", "wmv");
        FILE_EXT_MAP.put("text/html", "html");
        FILE_EXT_MAP.put("text/plain", "txt");
        FILE_EXT_MAP.put("text/xml", "xml");
        FILE_EXT_MAP.put("text/csv", "csv");
        FILE_EXT_MAP.put("application/msword", "doc");
        FILE_EXT_MAP.put("application/msword2007+", "docx");
        FILE_EXT_MAP.put("application/msexcell", "xls");
        FILE_EXT_MAP.put("application/msexcell2007+", "xlsx");
        FILE_EXT_MAP.put("audio/mpeg", "mp3");
        FILE_EXT_MAP.put("video/octet-stream", "flv");
        FILE_EXT_MAP.put("compressed/zip", "zip");
        FILE_EXT_MAP.put("compressed/rar", "rar");
    */

    public ListingAdapter(){
    }

    public String generateXML(Listing__c listing){
        XmlStreamWriter xmlWriter = new XmlStreamWriter();
        Property__c property;
        if(listing.Property__r == null) property = new Property__c();
        else property = listing.Property__r;
        
        // <project>
        xmlWriter.writeStartElement('', 'project', '');
        xmlWriter.writeAttribute('xmlns', '', 'b', McLabsConstants.RCM1_B_NAMESPACE);
        xmlWriter.writeAttribute('xmlns', '', 'i', McLabsConstants.RCM1_I_NAMESPACE);

            // <Address></Address>
            XMLHelper.writeGenericNode(xmlWriter, 'b', 'Address', '', property.Property_Address__c);

            // <AssetType></AssetType>
            String assetType = property.RecordType.Name;
            if(property.Primary_Use__c != null)
                assetType += ' - ' + property.Primary_Use__c;
            XMLHelper.writeGenericNode(xmlWriter, 'b', 'AssetType', '', assetType);
            
            if(property.Unit_Type__c == 'Bedrooms')
                // <Bedrooms></Bedrooms>
                xmlHelper.writeGenericNode(xmlWriter, 'b', property.Unit_Type__c, '', String.valueOf(property.Units__c));

            if(property.Unit_Type__c == 'Beds')
                // <Beds></Beds>
                xmlHelper.writeGenericNode(xmlWriter, 'b', property.Unit_Type__c, '', String.valueOf(property.Units__c));

            // <City></City>
            XMLHelper.writeGenericNode(xmlWriter, 'b', 'City', '', property.City__c);
            // <Class></Class>
            XMLHelper.writeGenericNode(xmlWriter, 'b', 'Class', '', property.Class__c);
            // <ClientId></ClientId>
            XMLHelper.writeGenericNode(xmlWriter, 'b', 'ClientId', '', listing.rcm1id__c);

            // <Contacts>
            xmlWriter.writeStartElement('b', 'Contacts', '');
            xmlWriter.writeAttribute('xmlns', '', 'c', McLabsConstants.RCM1_ARRAY_NAMESPACE);
                Integer i = 1;
                for(Broker__c broker : listing.Brokers1__r) {
                    XMLHelper.writeGenericNode(xmlWriter, 'c', 'string', '', broker.User__r.Email);
                }
            // </Contacts>
            xmlWriter.writeEndElement();
    
            // <Country></Country>
            XMLHelper.writeGenericNode(xmlWriter, 'b', 'Country', '', property.Country__c);
            // <County></County>
            XMLHelper.writeGenericNode(xmlWriter, 'b', 'County', '', property.County__c);
            // <LoanInterest></LoanInterest>          
            XMLHelper.writeGenericNode(xmlWriter, 'b', 'LoanInterest', '', String.valueOf(listing.Interest_Rate__c));
            // <LoanPerformance></LoanPerformance>
            XMLHelper.writeGenericNode(xmlWriter, 'b', 'LoanPerformance', '', listing.Loan_Performance__c);
            // <LoanType></LoanType>
            XMLHelper.writeGenericNode(xmlWriter, 'b', 'LoanType', '', listing.Loan_Type__c);
            // <Name></Name>
            XMLHelper.writeGenericNode(xmlWriter, 'b', 'Name', '', listing.Name);
            // <Occupancy></Occupancy>
            XMLHelper.writeGenericNode(xmlWriter, 'b', 'Occupancy', '', String.valueOf(property.Occupancy__c));
            // <ParcelSize></ParcelSize>
            xmlHelper.writeGenericNode(xmlWriter, 'b', 'ParcelSize', '', String.valueOf(property.Land_Acres__c));
            // <ProjectImage></ProjectImage>
            // <ProjectImageData></ProjectImageData>

            // <ProjectType></ProjectType>
            xmlHelper.writeGenericNode(xmlWriter, 'b', 'ProjectType', '', listing.Project_Type__c);
            

            if(property.Unit_Type__c == 'Rooms')
                // <Rooms></Rooms>
                XMLHelper.writeGenericNode(xmlWriter, 'b', 'Rooms', '', String.valueOf(property.Rooms__c));
                
            // <SquareFeet></SquareFeet>
            xmlHelper.writeGenericNode(xmlWriter, 'b', 'SquareFeet', '', String.valueOf(property.Square_Footage__c));
            // <State></State>
            XMLHelper.writeGenericNode(xmlWriter, 'b', 'State', '', property.State__c);
            // <Status></Status>
            xmlHelper.writeGenericNode(xmlWriter, 'b', 'Status', '', listing.Status__c);

            if(property.Unit_Type__c == 'Spaces')
                // <Spaces></Spaces>
                XMLHelper.writeGenericNode(xmlWriter, 'b', 'Spaces', '', String.valueOf(property.Parking_Spaces__c));
                
            // <Summary></Summary>
            XMLHelper.writeGenericNode(xmlWriter, 'b', 'Summary', '', listing.Offering_Notes__c);
            
            if(property.Unit_Type__c == 'Tenants')
                // <Tenants></Tenants>
                xmlHelper.writeGenericNode(xmlWriter, 'b', property.Unit_Type__c, '', String.valueOf(property.Units__c));

            if(property.Unit_Type__c == 'Units')
                // <Units></Units>
                xmlHelper.writeGenericNode(xmlWriter, 'b', property.Unit_Type__c, '', String.valueOf(property.Units__c));
            
            // <Value></Value>          
            XMLHelper.writeGenericNode(xmlWriter, 'b', 'Value', '', String.valueOf(listing.Asking_Price_Actual__c));
            // <YearBuilt></YearBuilt>
            xmlHelper.writeGenericNode(xmlWriter, 'b', 'YearBuilt', '', property.Year_Built__c);
            // <Zip></Zip>
            XMLHelper.writeGenericNode(xmlWriter, 'b', 'Zip', '', property.Zip_Code__c);
            
        // </project>
        xmlWriter.writeEndElement();
        
        return xmlWriter.getXmlString();
    }
    
    public McLabsObjects.ListingObject[] parseListings(String xmlString){
        Dom.Document xmlDoc = new Dom.Document();
        xmlDoc.load(xmlString);
        
        Dom.XmlNode rootElement = xmlDoc.getRootElement();
        Dom.Xmlnode bodyElement = rootElement.getChildElement('Body', S_NAMESPACE);
        Dom.Xmlnode retrieveProjectsResponseElement = bodyElement.getChildElement('RetrieveProjectResponse', 'http://tempuri.org/');
        Dom.Xmlnode retrieveProjectsResultElement = retrieveProjectsResponseElement.getChildElement('RetrieveProjectResult', 'http://tempuri.org/');
        Dom.Xmlnode tableElement = retrieveProjectsResultElement.getChildElement('Table', B_NAMESPACE);
        Dom.Xmlnode diffgramElement = tableElement.getChildElement('diffgram', DIFFGR_NAMESPACE);
        Dom.Xmlnode documentElement = diffgramElement.getChildElement('DocumentElement', '');
        Dom.Xmlnode[] projects = documentElement.getChildElements();

       McLabsObjects.ListingObject[] listings = new McLabsObjects.ListingObject[] {};
        
        for(Dom.XmlNode node : projects) {
            listings.add(parseListing(node));
        }
        
        return listings;
    }
    
    private McLabsObjects.ListingObject parseListing(Dom.XmlNode node){
        McLabsObjects.ListingObject listing   = new McLabsObjects.ListingObject();
        McLabsObjects.PropertyObject property = new McLabsObjects.PropertyObject();
        
        listing.name             = XMLHelper.parseStringNode(node,  'Name', null);

        property.streetAddress   = XMLHelper.parseStringNode(node,  'Address', null);
        property.city            = XMLHelper.parseStringNode(node,  'City', null);
        property.state           = XMLHelper.parseStringNode(node,  'State', null);
        property.zipCode         = XMLHelper.parseStringNode(node,  'Zip_x0020__x002F__x0020_Postal', null);
        property.county          = XMLHelper.parseStringNode(node,  'County', null);
        property.country         = XMLHelper.parseStringNode(node,  'Country', null);
        
        parseAssetType(node, property);
        listing.projectType      = XMLHelper.parseStringNode(node,  'Project_x0020_Type', null);
        
        listing.status           = XMLHelper.parseStringNode(node,  'Status', null);
        listing.askingPrice      = XMLHelper.parseDecimalNode(node, 'Value', null);
        
        property.yearBuilt       = XMLHelper.parseStringNode(node,  'Year_x0020_Built', null);
        property.squareFootage   = XMLHelper.parseIntegerNode(node, 'Square_x0020_Feet', null);
        property.landAcres       = XMLHelper.parseDecimalNode(node, 'Parcel_x0020_Size', null);
        
        parseUnits(node, property);
        
        property.occupancy       = XMLHelper.parseDecimalNode(node, 'Occupancy', null);
        property.clazz           = XMLHelper.parseStringNode(node,  'Class', null);
        
        listing.notes            = XMLHelper.parseStringNode(node,  'Summary', null);
        listing.rcm1id           = XMLHelper.parseStringNode(node,  'Client_x0020_ID', null);
        listing.loanType         = XMLHelper.parseStringNode(node,  'Loan_x0020_Type', null);
        listing.loanPerformance  = XMLHelper.parseStringNode(node,  'Loan_x0020_Performance', null);
        listing.interestRate     = XMLHelper.parseStringNode(node,  'Loan_x0020_Interest', null);
        
        parseAttachments(node, property);
        
        listing.property         = property;
        
        Integer i = 1;
        String email;
        while((email = XMLHelper.parseStringNode(node, 'Contact_x0020_' + i++ + '_x0020_Email', null)) != null) {
            McLabsObjects.BrokerObject broker = new McLabsObjects.BrokerObject();
            broker.email = email;
            
            listing.brokers.add(broker);
            
            system.debug('adding broker: ' + email + ' (' + listing.brokers.size() +  ')');
        }

        return listing;
    }
    
    private void parseAssetType(Dom.XmlNode node, McLabsObjects.PropertyObject property){
        String assetType = XMLHelper.parseStringNode(node, 'Asset_x0020_Type', null);
        if(assetType == null) return;
        String[] assetTypeArr = assetType.split(' - ');
        
        String recordTypeStr = assetTypeArr[0];
        String primaryUseStr = (assetTypeArr.size() > 1) ? assetTypeArr[1] : null;
        
        //recordTypeStr = recordTypeStr.replaceAll('[^\\w]', '_');
        //system.debug('record type: ' + recordTypeStr);
        
        RecordType[] recordTypes = [select Id from RecordType where Name = :recordTypeStr];
        
        if(recordTypes != null && !recordTypes.isEmpty())
            property.recordTypeId = recordTypes[0].Id;
        
        property.primaryUse = primaryUseStr;
    }
    
    private void parseUnits(Dom.XmlNode node, McLabsObjects.PropertyObject property){
        String unitType = XMLHelper.parseStringNode(node, 'Unit_x0020_Type', null);
        if     (unitType == 'Units'   ) property.units          = XMLHelper.parseIntegerNode(node, 'Units',    null);
        else if(unitType == 'Bedrooms') property.units          = XMLHelper.parseIntegerNode(node, 'Bedrooms', null);
        else if(unitType == 'Beds'    ) property.units          = XMLHelper.parseIntegerNode(node, 'Beds',     null);
        else if(unitType == 'Rooms'   ) property.rooms          = XMLHelper.parseIntegerNode(node, 'Rooms',    null);
        else if(unitType == 'Spaces'  ) property.parkingSpaces  = XMLHelper.parseIntegerNode(node, 'Spaces',   null);
        else if(unitType == 'Tenants' ) property.units          = XMLHelper.parseIntegerNode(node, 'Tenants',  null);
        
        property.unitType = unitType;
    }
    
    private void parseAttachments(Dom.XmlNode node, McLabsObjects.PropertyObject property){
        
    }
        
}