src/objects/Broker__c.object
<CustomObject>
    <description>Archived system function</description>
    <fields>
        <fullName>Escrow__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Escrow</label>
        <referenceTo>Escrow__c</referenceTo>
        <relationshipName>Brokers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Listing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipName>Brokers1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>system.broker</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Broker&apos;s ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>system.brokers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Buyer__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Listings</relationshipLabel>
        <relationshipName>Buyers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Listing__c</fullName>
        <label>Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipLabel>Buyers</relationshipLabel>
        <relationshipName>Buyers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Buyer</label>
    <nameField>
        <displayFormat>BUYER_{000000}</displayFormat>
        <label>Buyer&apos;s ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Buyers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Commission__c.object
<CustomObject>
    <fields>
        <fullName>Broker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Internal Agent</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Escrow__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Do not adjust. The system will update automatically.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Escrow__c</referenceTo>
        <relationshipLabel>Commissions</relationshipLabel>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Listing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Do not adjust. The system will update automatically.</inlineHelpText>
        <label>Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipLabel>Commissions</relationshipLabel>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Do not adjust. The system will update automatically.</inlineHelpText>
        <label>Proposal</label>
        <referenceTo>Proposal__c</referenceTo>
        <relationshipLabel>Commissions</relationshipLabel>
        <relationshipName>Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Commission</label>
    <nameField>
        <displayFormat>C-{00000000}</displayFormat>
        <label>Commission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Escrow__c.object
<CustomObject>
    <fields>
        <fullName>Buyer_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Buyer Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects (Buyer Company)</relationshipLabel>
        <relationshipName>Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Buyer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Buyer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Projects (Buyer)</relationshipLabel>
        <relationshipName>Projects2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Escrow__c</fullName>
        <label>Commission ($)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Landlord_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Landlord Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects (Landlord Company)</relationshipLabel>
        <relationshipName>Projects2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Landlord__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Landlord</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Projects (Landlord)</relationshipLabel>
        <relationshipName>Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Listing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assignment</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Escrows</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Probability__c</fullName>
        <defaultValue>0.75</defaultValue>
        <inlineHelpText>What is the probability of this project closing?</inlineHelpText>
        <label>Probability</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Escrows</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created for third project requirements.</description>
        <label>Proposal</label>
        <referenceTo>Proposal__c</referenceTo>
        <relationshipName>Escrows</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Seller_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Seller Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Seller__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created as requirement from third project.</description>
        <label>Seller</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Escrows4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Commis__c</fullName>
        <defaultValue>false</defaultValue>
        <label>System_Commis</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tenant_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tenant Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects (Tenant Company)</relationshipLabel>
        <relationshipName>Projects3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tenant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tenant</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Projects (Tenant)</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Listing__c.object
<CustomObject>
    <fields>
        <fullName>Client_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commission_Input__c</fullName>
        <inlineHelpText>Please estimate for pipeline tracking purposes</inlineHelpText>
        <label>Commission ($)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Commission__c</fullName>
        <label>Commission (%)</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Owner_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Listings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Probability__c</fullName>
        <defaultValue>0.40</defaultValue>
        <inlineHelpText>What is the probability of this assignment closing?</inlineHelpText>
        <label>Probability</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipName>Listings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Added for the third project requirement.</description>
        <label>Proposal</label>
        <referenceTo>Proposal__c</referenceTo>
        <relationshipName>Listings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Commis__c</fullName>
        <defaultValue>false</defaultValue>
        <label>System_Commis</label>
        <type>Checkbox</type>
    </fields>
    <label>Listing</label>
    <nameField>
        <label>Listing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Proposal__c.object
<CustomObject>
    <fields>
        <fullName>Client_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commission__c</fullName>
        <inlineHelpText>Please estimate for pipeline tracking purposes</inlineHelpText>
        <label>Commission ($)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Proposal</label>
    <nameField>
        <label>Proposal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Escrow__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Escrow__c</referenceTo>
        <relationshipLabel>Parties to the Transaction</relationshipLabel>
        <relationshipName>Parties_to_the_Transaction</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Seller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buyer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lessee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lessor</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transcation_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Parties to the Transaction</relationshipLabel>
        <relationshipName>Parties_to_the_Transaction</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Party to the Transaction</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parties to the Transaction</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AssignmentProjectController.cls
/**
 * Shrew Designs
 * converts the Assignment to a Project and updates Assignment Status to [In Contract]
 *@author: Chetan Garg
 */ 
public  class AssignmentProjectController {
    public string listingId {get;set;}
    public AssignmentProjectController(ApexPages.StandardController stdCon){
        listingId = stdCon.getId();
    }
    
    public Pagereference createProject(){
        Pagereference pg = null;
        RecordType projectRecordType = null;
        try{
            Listing__c listing = [Select id,RecordTypeId, Property__c, Proposal__c, Owner_Contact__c,Client_Company__c, Name,OwnerId,Commission_input__c,probability__c
                                    , (Select Id, Listing__c, Seller__c,Landlord__c From Escrows__r), (Select Id, Listing__c From Commissions__r)
                                    ,RecordType.Name 
                                  From Listing__c
                                  Where id=:listingid];
            List<Escrow__c> escrowList = new List<Escrow__c>();
            if(listing.Escrows__r.size() == 0){
                Escrow__c escrow = new Escrow__c();
                escrow.Listing__c = listing.Id;     
                escrow.Name = listing.Name;// + ' - ' +  System.now().format('MM/dd/yy  hh:mm a');
                
                if(listing.Property__c != null){
                    escrow.Property__c = listing.Property__c;
                }       
                
                escrow.escrow__c = listing.Commission_input__c;
                //escrow.probability__c = listing.probability__c;
                escrow.System_Commis__c = true;
                
                if(listing.Proposal__c != null){
                    escrow.Proposal__c = listing.Proposal__c;
                }                   
                
                //if(listing.Owner_Contact__c != null){
                    
                //}
                
                
                //Populate Project's Record TypeId based on listing record Type Id
                if(AssignmentTriggerHelper.getProjectRecordTypeId(listing.recordTypeId) != null){
                	escrow.recordTypeId = AssignmentTriggerHelper.getProjectRecordTypeId(listing.recordTypeId);
                }
                
                for(RecordType rt :[Select id ,Name from RecordType where id=:escrow.recordTypeId]){
                	projectRecordType = rt;
                }
                
                if(listing.recordType.Name == 'Tenant Representation'){
                	escrow.Tenant_Company__c = listing.Client_Company__c;
                	escrow.Tenant__c = listing.Owner_Contact__c;
                }else if(listing.recordType.Name == 'Landlord Representation'){
                	escrow.Landlord_Company__c = listing.Client_Company__c;
                	escrow.Landlord__c = listing.Owner_Contact__c;
                }else if(listing.recordType.Name == 'Seller Representation'){	
                	escrow.Seller_Company__c = listing.Client_Company__c;
                	escrow.Seller__c = listing.Owner_Contact__c;	
                }else{
                	escrow.Buyer__c = listing.Owner_Contact__c;
                	escrow.Buyer_Company__c = listing.Client_Company__c;
                }
                
                
                escrowList.add(escrow);
                upsert escrow;
            }else{
                escrowList = listing.Escrows__r;
            }
            
            for(Escrow__c e : escrowList){              
                for(Commission__c c: listing.Commissions__r){
                    if(e.Listing__c == c.Listing__c){
                        c.Escrow__c = e.Id;
                        c.Listing__c = null;
                    }       
                }
                
                if(listing.Commissions__r.size() == 0 ){
					Commission__c comm = new Commission__c();
					comm.broker__c = listing.OwnerId;
					comm.Escrow__c = e.id;
					//comm.Listing__c = listing.id;
					insert comm;
				}
            }   
            upsert listing.Commissions__r;
            
            Transaction__c[] sellers = new Transaction__c[]{};
    
            for(Escrow__c escrow : escrowList) {
            	Transaction__c party = new Transaction__c();
            	party.Escrow__c = escrow.Id;
            	party.Transcation_Company__c = listing.Client_Company__c;
                party.Contact__c = listing.Owner_Contact__c;
            	if(listing.recordType.Name == 'Tenant Representation'){
                	party.Role__c = 'Tenant';
                }else if(listing.recordType.Name == 'Buyer Representation'){
                	party.Role__c = 'Buyer';
                }else if(listing.recordType.Name == 'Seller Representation'){	
                	party.Role__c = 'Seller';
                }else{
                	party.Role__c = 'Landlord';
                }
                sellers.add(party);
            }
            
            insert(sellers);
            
            listing.Status__c = 'In Contract';
            update listing;
        
            return new Pagereference('/' + (listing.Escrows__r.size() > 0 ? listing.Escrows__r[0].id : escrowList[0].id) );
        }catch(Exception ex){
            Apexpages.addMessages(ex);
        }
        return pg;
    }

}