src/objects/Buyer__c.object
<CustomObject>
    <label>Buyer</label>
    <nameField>
        <displayFormat>BUYER_{000000}</displayFormat>
        <label>Buyer&apos;s ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Buyers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Commission_Item__c.object
<CustomObject>
    <description>A list of items that are used to calculate commissions. For example, in a lease comp this will be made up of all of the rent times the commission percent for each lease period.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>The total consideration for this line item.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Area_Sq_Ft__c</fullName>
        <inlineHelpText>The size of the space in square feet.</inlineHelpText>
        <label>Area (Sq Ft)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Commission_Amount__c</fullName>
        <formula>Total__c * Commission_Percent__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Commission ($)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Commission_Percent__c</fullName>
        <label>Commission (%)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Comp__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Comp</label>
        <referenceTo>Sale__c</referenceTo>
        <relationshipLabel>Commission Items</relationshipLabel>
        <relationshipName>Commission_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <inlineHelpText>The order that this item will show up on the Comp and the Invoice</inlineHelpText>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rent_Sq_Ft__c</fullName>
        <label>Rent/Sq Ft</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <formula>Amount__c *  Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>$/SF/Year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$/SF/Month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amount/Year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amount/Month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>% of Sale Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>% of  Flat Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negotiated Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Brokerage Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonus per Square Feet</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Commission Item</label>
    <nameField>
        <displayFormat>Item-{00000}</displayFormat>
        <label>Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commission Items</pluralLabel>
    <recordTypes>
        <fullName>Sale</fullName>
        <active>true</active>
        <label>Sale</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Comp__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Comp</label>
        <referenceTo>Sale__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Paid__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Paid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Percent_Due__c</fullName>
        <label>Percent Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Recipient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recipient</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subtotal__c</fullName>
        <formula>Total_Commissions__c * IF(ISBLANK( Percent_Due__c ),1,Percent_Due__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Subtotal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <label>Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Commissions__c</fullName>
        <formula>Comp__r.Commission__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The total commissions from the Comp</inlineHelpText>
        <label>Total Commissions</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Due__c</fullName>
        <formula>Subtotal__c +  Tax__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Due</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{000}{DD}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sale__c.object
<CustomObject>
    <fields>
        <fullName>Buyer_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Buyer Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Comps (Buyer Company)</relationshipLabel>
        <relationshipName>Comps3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Buyer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Buyer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Comps (Buyer)</relationshipLabel>
        <relationshipName>Comps1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commission_Percent__c</fullName>
        <label>Commission (%)</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Property_Address__c</fullName>
        <formula>if( Property__c =&quot;&quot;,  Property_Leases__r.Property_Address__c ,  Property__r.Property_Address__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Property Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_City__c</fullName>
        <formula>if( Property__c =&quot;&quot;, Property_Leases__r.City__c ,  Property__r.City__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Property City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <formula>if( Property__c =&quot;&quot;,  text(Property_Leases__r.State__c), text( Property__r.State__c ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Property State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Zip_Postal_Code__c</fullName>
        <formula>if( Property__c =&quot;&quot;,  Property_Leases__r.Zip_Code__c ,  Property__r.Zip_Code__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Property Zip/Postal Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rental_Rate_Type__c</fullName>
        <label>Rental Rate Type</label>
        <picklist>
            <picklistValues>
                <fullName>$/SF/Year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$/SF/Month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amount/Year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amount/Month</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Comp</label>
    <nameField>
        <label>Comp Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comps</pluralLabel>
    <recordTypes>
        <fullName>Sale</fullName>
        <active>true</active>
        <label>Sale</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/InvoicePDFController.cls
public with sharing class InvoicePDFController {
    public string InvoiceId {get; set;}
    private Invoice__c invoice;
    public Commission_Item__c[] CommissionItems {get; private set;}
        
    public String companyLogoUrl {get; private set;}
    
    public String compRecordTypeId {get; private set;}
    public String compSaleRecordTypeId {get; private set;}
    public boolean isSaleRecordType {get; set;} 
    
    private static Map<string,Id> CompsRecordTypes = RecordTypeManager.GetRecordTypeIdsByDeveloperName(Sale__c.SObjectType);
    
  
        
    public InvoicePDFController(ApexPages.StandardController stdCon){
            invoice = (Invoice__c) stdCon.getRecord();
            invoiceid = invoice.id;
            getInvoice();
            
            /*
                Added by:  Hitendra 
                Date: 06-Mar-2014
                Issue #17 Invoice Settings 
             */
            compRecordTypeId = invoice.Comp__r.recordTypeId;
            compSaleRecordTypeId = CompsRecordTypes.get('Sale');
            isSaleRecordType = (compRecordTypeId == compSaleRecordTypeId);
            
            companyLogoUrl = getComponyLogoUrl();
    }
        
    public InvoicePDFController(){
        invoiceid = invoice.id;
        getInvoice();
    }

    public Invoice__c getInvoice(){
        if(InvoiceId!=null&&invoice==null){
            invoice = [Select i.Total_Due__c, i.Tax__c, i.SystemModstamp, i.Subtotal__c, 
                i.Recipient__c, i.Percent_Due__c, i.Paid__c, i.OwnerId, i.Name, i.LastViewedDate, i.LastReferencedDate, 
                i.LastModifiedDate, i.LastModifiedById, i.LastActivityDate, i.IsDeleted, i.Invoice_Date__c, i.Id, 
                i.Due_Date__c, i.CreatedDate, i.CreatedById, i.Comp__r.Property_Zip_Postal_Code__c, i.Comp__r.Property_State__c, 
                i.Comp__r.Property_City__c, i.Comp__r.Property_Address__c, i.Comp__r.Buyer__c, i.Comp__r.Buyer_Company__c, 
                i.Comp__r.RecordType.DeveloperName, i.Comp__r.Rental_Rate_Type__c, i.Comp__c, i.Total_Commissions__c, i.Comp__r.RecordTypeId  
                From Invoice__c i
                where i.Id = :InvoiceId];
                
        }
        if(InvoiceId!=null&&commissionitems==null){
            CommissionItems = [Select c.Type__c, c.Total__c, c.Rent_Sq_Ft__c, c.Quantity__c, c.Order__c, c.Name, 
                        c.LastModifiedDate, c.LastModifiedById, c.IsDeleted, c.Id, c.CreatedDate, c.CreatedById, c.Comp__c, 
                        c.Commission_Percent__c, c.Commission_Amount__c, c.Area_Sq_Ft__c, c.Amount__c 
                                From Commission_Item__c c
                                where c.Comp__c = :invoice.Comp__c
                                order by c.Order__c asc];
        }
        return invoice;
    }
    
    public string getCompRecordType(){
        return invoice.Comp__r.RecordType.DeveloperName;
    }
    
     /*
        Added by:  Roshan 
        Date: 06-Mar-2014
        Issue #16 Invoice Settings 
     */
    private String getComponyLogoUrl() {
        list<Document> documentList = [select Id from Document where DeveloperName='Company_Logo'];
        Document companyLogoDoc = (documentList != null && documentList.size()>0)? documentList[0] : null;
        
        return (companyLogoDoc != null)? '/servlet/servlet.FileDownload?file=' + companyLogoDoc.Id : '';
    } 

}