src/objects/Escrow__c.object
<CustomObject>
    <fields>
        <fullName>Escrow__c</fullName>
        <label>Commission ($)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Escrow_Task__c.object
<CustomObject>
    <description>Archived system function</description>
    <fields>
        <fullName>Escrow__c</fullName>
        <formula>HYPERLINK(Project_Milestone__r.Escrow__c, Project_Milestone__r.Escrow__r.Name,&apos;_self&apos;)</formula>
        <inlineHelpText>A link to the Project which this task is included in via its milestone.</inlineHelpText>
        <label>Escrow</label>
        <type>Text</type>
    </fields>
    <label>system.project task</label>
    <nameField>
        <label>Escrow Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>system.project tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Milestone1_Milestone__c.object
<CustomObject>
    <fields>
        <fullName>Escrow__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The project this milestone is assigned to. If this is a sub-milestone this field is empty.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Escrow__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Project_Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Milestone1_TestProjectBuilder.cls
public with sharing class Milestone1_TestProjectBuilder {

	public Integer numberMilestones { get; set; }
	public Integer numberTasks {get; set; }
	
	public void buildProject() {
		
		Escrow__c newProject = Milestone1_Test_Utility.sampleProjectActive('Sample ' + Datetime.now());
		insert newProject;
		
		for (Integer i=0; i < numberMilestones; i++) {
			Milestone1_Milestone__c ms = Milestone1_Test_Utility.sampleMilestone(newProject);
			insert ms;
			for (Integer j=0; j < numberTasks; j++) {
				Escrow_Task__c task = Milestone1_Test_Utility.sampleTask(ms);
				insert task;
				
			}
		}
		
	}
}