src/objects/Escrow__c.object
<CustomObject>
    <fields>
        <fullName>Escrow__c</fullName>
        <label>Commission ($)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProjectRecordTypeMapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Project to Comp record type mapping</description>
    <fields>
        <fullName>CompRecordType__c</fullName>
        <label>Comp Record Type</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Project Record Type Mapping</label>
</CustomObject>

src/objects/Sale__c.object
<CustomObject>
    <fields>
        <fullName>Escrow__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Escrow</label>
        <referenceTo>Escrow__c</referenceTo>
        <relationshipName>Sales</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Comp</label>
    <nameField>
        <label>Comp Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EscrowTriggerHelper.cls
/**
 * Shrew Designs
 * Helper class for Project Trigger
 *@author: Chetan Garg
 */ 
public class EscrowTriggerHelper {
	//Project to Comp Record Type Mapping
	private static Map<Id,Id> escrowToCompRecordType;
	//Return Assignment recordType from Propsal RecordTypeId
	public static Id getCompRecordTypeId(Id projectRecordTypeId){
		if(escrowToCompRecordType == null){
			escrowToCompRecordType = new Map<Id,Id>();
			Map<String,ProjectRecordTypeMapping__c> mapping = ProjectRecordTypeMapping__c.getAll();
			Map<String,Id> mapSaleRecordType = new Map<String,Id>();
			for(RecordType rt :[select id, name from RecordType where sObjecttype = 'Sale__c']){
				mapSaleRecordType.put(rt.Name,rt.id);
			}
			
			for(RecordType rt : [select id, name from RecordType where sObjecttype = 'Escrow__c']){
				if(mapping.containskey(rt.Name)){
					escrowToCompRecordType.put(rt.id,
							 mapSaleRecordType.get(mapping.get(rt.Name).CompRecordType__c)
							);
				}
			} 	
			
		}
		return escrowToCompRecordType.get(projectRecordTypeId);	
	}
	
	
}