src/objects/Listing__c.object
<CustomObject>
    <fields>
        <fullName>Proposal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Added for the third project requirement.</description>
        <label>Proposal</label>
        <referenceTo>Proposal__c</referenceTo>
        <relationshipName>Listings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Listing</label>
    <nameField>
        <label>Listing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Proposal__c.object
<CustomObject>
    <label>Proposal</label>
    <nameField>
        <label>Proposal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProposalRecordtypeMapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Proposal to Assignment Record type mapping</description>
    <fields>
        <fullName>AssignmentRecordType__c</fullName>
        <description>Assignment Record type Name</description>
        <inlineHelpText>Assignment Record type Name</inlineHelpText>
        <label>Assignment RecordType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Proposal Record Type Mapping</label>
</CustomObject>

src/classes/ProposalTriggerHelper.cls
/**
 * Shrew Designs
 * Helper class for Proposal Trigger
 *
 *@author: Chetan Garg
 */ 
public class ProposalTriggerHelper {
	private static Map<Id,Id> pToAssignmentMapping;
	//Return Assignment recordType from Propsal RecordTypeId
	public static Id getAssignmentRecordType(Id proposalRecordType){
		if(pToAssignmentMapping == null){
			pToAssignmentMapping = new Map<Id,Id>();
			Map<String,ProposalRecordtypeMapping__c> mapping = ProposalRecordtypeMapping__c.getAll();
			Map<String,Id> mapAssignmentRecordType = new Map<String,Id>();
			for(RecordType rt :[select id, name from RecordType where sObjecttype = 'Listing__c']){
				mapAssignmentRecordType.put(rt.Name,rt.id);
			}
			
			for(RecordType rt :[select id, name from RecordType where sObjecttype = 'Proposal__c']){
				if(mapping.containskey(rt.Name)){
					pToAssignmentMapping.put(rt.id,
							 mapAssignmentRecordType.get(mapping.get(rt.Name).AssignmentRecordType__c)
							);
				}
			} 	
			
		}
		return pToAssignmentMapping.get(proposalRecordType);	
	}
	
	
}