src/objects/Ownership__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <formula>Property__r.City__c</formula>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipName>Contact_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>TEXT(Property__r.State__c )</formula>
        <label>State</label>
        <type>Text</type>
    </fields>
    <label>Ownership</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Ownership ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ownership</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ORANGE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OKALOOSA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OKLAHOMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alamance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albemarle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alexander</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alleghany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archdale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ashe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bath</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beaufort</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bertie</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bladen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brunswick</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buncombe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burke</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bute</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cabarrus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caldwell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Camden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carteret</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caswell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Catawba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chatham</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cherokee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cherokee Reservation (Qualla Boundary)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chowan</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Property_Address__c</fullName>
        <label>Property Address</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip/Postal Code</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PropertyMapRelatedListController.cls
/**
 * Riptide Software
 *
 * This controller manages the PropertyMapRelatedList visual force page. It pulls a list of properties based on the 
 * contact selected and pushes the data to a Google Maps visual force component to be rendered. 
 *
 *@author: Trey Dickson
 */	

public with sharing class PropertyMapRelatedListController {

	public boolean showMap {get;set;}
	public boolean notFound {get;set;}
	public AddressModel addressmodel {get;set;}

	public ApexPages.StandardSetController setCon {
		get {
			if(setCon == null)	{
				//Get the list of ownership records for the contact
				List<Ownership__c> ownership = [SELECT Property__c FROM Ownership__c WHERE Contact__c = :ApexPages.currentPage().getParameters().get('id')];
				System.Debug('&&&&&&&&&&&&&&&&&&&&& ' + ownership.size());
				Set<String> properties = new Set<String>();
				
				//Build a list of properties ids
				for(Ownership__c owner : ownership) {
					properties.add(owner.Property__c);
				}
				System.Debug('&&&&&&&&&&&&&&&&&&&&& ' + properties.size());
				
				//pull the properties for the contact and set them to the StandardSetController
				setCon = new ApexPages.StandardSetController(Database.getQueryLocator([SELECT id, Name, Property_Address__c, City__c, state__c, County__c, Zip_Code__c from Property__c WHERE ID IN :properties]));
				
			}
			return setCon;
		}
		set;
	}
	
	public PropertyMapRelatedListController() {
		//Create an address model to place the 
		addressmodel = new AddressModel();
		
		//Get the list of properties
		List<Property__c> properties = getProperties();
		
		for(Property__c property : properties) {
            showMap = true;
            //Check to see if the property has all the address fields filled out
            if(property.Property_Address__c == null || property.Property_Address__c == '' ||
               property.City__c == null || property.City__c == '' ||
               property.state__c == null || property.state__c == '' ||
               property.Zip_Code__c == null || property.Zip_Code__c == '')
               {
                notFound = true;
            } else {
            
	            string address = property.Property_Address__c != null ? property.Property_Address__c.replaceall('\n','') :  '';
	            
	            if(address.trim().length() > 0 )
	                address += ',';
	            address += property.City__c != null ? property.City__c.replaceall('\n','') :  '';
	            
	            if(address.trim().length() > 0 )
	                address += ',';       
	            address += property.state__c != null ? property.state__c : '';
	
	            if(address.trim().length() > 0 )
	                address += ',';       
	            address += property.Zip_Code__c != null ? property.Zip_Code__c : '';
	            
	            //Add the address tot he list of address models
	            addressmodel.add(address,
	                             '',
	                             '',
	                             '<h3><a href=/' + property.id + ' target=_blank>' + property.name + '</a></h3>' +
	                             '<br>' + address);
            
            }
		}
	}
	
	public List<Property__c> getProperties() {
		return (List<Property__c>) setCon.getRecords();
	}
	
	private static testMethod void testController() {
		//Test the controller
		Property__c prop1 = new Property__c();
		prop1.Name = 'hi';
		prop1.Property_Address__c = '123 N Alafaya Trl';
		prop1.City__c = 'Orlando';
		prop1.State__c = 'FL';
		prop1.Zip_Code__c = '55555';
		
		insert prop1;
		
		Property__c prop2 = new Property__c();
		prop2.Name = 'Hi';
		prop2.Property_Address__c = '123 N Alafaya trl';
		
		insert prop2;
		
		Contact contact = new Contact();
		contact.LastName = 'James';
		
		insert contact;
		
		Ownership__c ownership = new Ownership__c();
		ownership.Contact__c = contact.Id;
		ownership.Property__c = prop1.Id;
		
		insert ownership;
		
		ownership = new Ownership__c();
		ownership.Contact__c = contact.Id;
		ownership.Property__c = prop2.Id;
		
		insert ownership;
		
		PageReference pageRef = new Pagereference('/apex/PropertyMapRelatedList?id=' + contact.Id);
		Test.setCurrentPage(pageref);
		
		PropertyMapRelatedListController controller = new PropertyMapRelatedListController();
	}
}