src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Square_Footage__c</fullName>
        <label>Square Footage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Existing</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Under Construction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Renovation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proposed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Demolished</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Spaces__c.object
<CustomObject>
    <fields>
        <fullName>Asking_Rate_PSF__c</fullName>
        <label>Rental Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date_Available__c</fullName>
        <label>Date Available</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lease_Expiration_Date__c</fullName>
        <label>Lease Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lease_Term_Months__c</fullName>
        <label>Lease Term (Months)</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lease_Type__c</fullName>
        <label>Lease Type</label>
        <picklist>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NNN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Modified Gross</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Modified Net</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industrial Gross</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Property_Type__c</fullName>
        <label>Space Type</label>
        <picklist>
            <picklistValues>
                <fullName>Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industrial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Land</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Special Purpose</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Spaces</relationshipLabel>
        <relationshipName>Spaces</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Space_Sub_Type__c</fullName>
        <label>Space Sub-Type</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industrial- Flex Space</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industrial- Manufacturing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industrial- Office Showroom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industrial- R&amp;D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industrial- Truck Terminal/Hub</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industrial- Warehouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industrial- Distribution Warehouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industrial- Refrigerated/Cold Storage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Land- Industrial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Land- Multifamily</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Land- Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Land- Residential</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Land- Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Land- Commercial(Other)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Office- Creative/Loft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Office- Office Building</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Office- Governmental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Office- Medical Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Office- R&amp;D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail- Restaurant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail- Freestanding Building</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail- Retail (Other)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail- Vehicle Related</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail- Pad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail- Anchor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail- Community Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail- Strip Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail- Specialty Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail- Neighborhood Center</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Square_Footage__c</fullName>
        <label>Available Square Footage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Available</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leased</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Suite_Floor__c</fullName>
        <label>Suite/Floor #</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Space</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Spaces Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PropertySpacesController.cls
/*
This class contains methods for rendering the stacking plan.
*/

public with sharing class PropertySpacesController {

    public List<String> spaceNames;
    private ApexPages.StandardController stdController;
    public PropertySpacesController (ApexPages.StandardController stdController){
        this.stdController = stdController;
    }
    
    public map<string,list<Spaces__c>> getSpacesbyFloor(){
        map<string,list<Spaces__c>> FloorMap = new map<string,list<Spaces__c>>();
        for(Spaces__c s : getSpaces()){
            string Floor = s.Suite_Floor__c == null ? 'Unknown' : s.Suite_Floor__c.left(1);
            if(FloorMap.containsKey(Floor )){
                FloorMap.get(Floor).add(s);
            }else{
                FloorMap.put(Floor,new list<Spaces__c>{s});
            }
        }
        return FloorMap;
    }
    
    public map<string,decimal> getSquareFootagebyFloor(){
        map<string,decimal> SqFootageMap = new map<string,decimal>();
        for(Spaces__c s : getSpaces()){
            string Floor = s.Suite_Floor__c == null ? 'Unknown' : s.Suite_Floor__c.left(1);
            if(SqFootageMap.containsKey(Floor )){
                SqFootageMap.put(Floor, SqFootageMap.get(Floor) + s.Square_Footage__c);
            }else{
                SqFootageMap.put(Floor,s.Square_Footage__c);
            }
        }
        return SqFootageMap;
    }
    
    public transient list<Spaces__c> spaces;
    public list<Spaces__c> getSpaces(){
        if(spaces==null){
            spaces = [Select m.Suite_Floor__c, m.Status__c, m.Space_Sub_Type__c, m.Property_Type__c, m.Lease_Type__c, m.Lease_Term_Months__c, m.Lease_Expiration_Date__c, 
                m.Date_Available__c, m.Asking_Rate_PSF__c, m.Id, m.Square_Footage__c
                From Spaces__c m 
                WHERE m.Property__c = :stdController.getId()
                Order by m.Suite_Floor__c desc ];
        }
        return spaces;
    }

}