src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Property_Address__c</fullName>
        <label>Property Address</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PropertyImageController.cls
public class PropertyImageController{
     public string propertyid{get;set;}
     public Property__c property;
     
    public PropertyImageController(ApexPages.StandardSetController controller) {
                property   = (Property__c)controller.getRecord();
                string pageref=ApexPages.currentPage().getParameters().get('id');
                propertyid = pageref;
    }
    
    private static testMethod void PropertyImageControllerTest() {
        Property__c p = new Property__c();
    	p.Property_Address__c = 'test';
    	insert p;
    	Property__c[] props = new Property__c[]{};
    	props.add(p);
    	//PageReference page = new PageReference('/apex/PropertyImage');
    	ApexPages.StandardSetController con = new ApexPages.StandardSetController(props);
    	PropertyImageController controller = new PropertyImageController(con);
    }
}