src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ORANGE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OKALOOSA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OKLAHOMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alamance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albemarle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alexander</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alleghany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archdale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ashe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bath</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beaufort</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bertie</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bladen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brunswick</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buncombe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burke</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bute</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cabarrus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caldwell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Camden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carteret</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caswell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Catawba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chatham</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cherokee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cherokee Reservation (Qualla Boundary)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chowan</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Property_Address__c</fullName>
        <label>Property Address</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip/Postal Code</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PropertyMapcontroller.cls
/************************************************************************************************
@ name          :  PropertyMapcontroller
page            :  PropertyMap
@ author        :  iBirds Services
@ date          :  14 May, 2011
@ description   :  This is the class to provide the address and functionality to the page.
************************************************************************************************/

public with sharing class PropertyMapcontroller{
    public AddressModel addressmodel {get;set;}
    String propertyid;
    Property__c property;
    public boolean showMap {get;set;}
    public PropertyMapcontroller(ApexPages.StandardController sc){
    	
    	
    	//String s = rcm1Api.getProjects().getBody();
    	//ProjectAdapter pa = new ProjectAdapter(s); 
    	
    	
        property = (Property__c)sc.getRecord();
        addressmodel = new AddressModel();

        if(property.Id != null){
            for(Property__c property: [Select id, Name, Property_Address__c, City__c, state__c, County__c, Zip_Code__c from Property__c where id =:property.Id]){
            showMap = true;
            if(property.Property_Address__c == null || property.Property_Address__c == '' ||
               property.City__c == null || property.City__c == '' ||
               property.state__c == null || property.state__c == '' ||
               property.Zip_Code__c == null || property.Zip_Code__c == ''){
                showMap = false;
            }
            
            string address = property.Property_Address__c != null ? property.Property_Address__c.replaceall('\n','') :  '';
            
            if(address.trim().length() > 0 )
                address += ',';
            address += property.City__c != null ? property.City__c.replaceall('\n','') :  '';
            
            if(address.trim().length() > 0 )
                address += ',';       
            address += property.state__c != null ? property.state__c : '';

            if(address.trim().length() > 0 )
                address += ',';       
            address += property.Zip_Code__c != null ? property.Zip_Code__c : '';
            
            addressmodel.add(address,
                             '',
                             '',
                             '<h3><a href=/' + property.id + ' target=_blank>' + property.name + '</a></h3>' +
                             '<br>' + address);
            }
    
        }
    }    
    
    private static testMethod void test(){
    	Property__c p = new Property__c();
    	p.Property_Address__c = 'test';
    	insert p;
    	PropertyMapcontroller controller = new PropertyMapcontroller(new ApexPages.Standardcontroller(p));
    }
}