src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Last_Sale_Date__c</fullName>
        <label>Last Sale Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Sale_Price__c</fullName>
        <label>Last Sale Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Property_Address__c</fullName>
        <label>Property Address</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sale__c.object
<CustomObject>
    <fields>
        <fullName>Property_Address__c</fullName>
        <formula>if( Property__c =&quot;&quot;,  Property_Leases__r.Property_Address__c ,  Property__r.Property_Address__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Property Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property Sold</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Sale Comps</relationshipLabel>
        <relationshipName>Sales</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sale_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sale_Price__c</fullName>
        <label>Sale Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Comp</label>
    <nameField>
        <label>Comp Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchSalePriceUpdate.cls
/*** Update Property Address to Contact record
   *
   *  Version 1.0  -- Shrew Design  -- 
   *
  ***/
  
/*** To Run this Class From the Console:
     
id batchId = Database.executeBatch(new BatchSalePriceUpdate(), 200);
System.debug('\n\n==> batchId = ' + batchId); 

***/
global class BatchSalePriceUpdate implements Database.Batchable<SObject> {

  global Database.QueryLocator start(Database.BatchableContext context) {

    Database.QueryLocator ans = 
       Database.getQueryLocator('Select id, Last_Sale_Price__c, Last_Sale_Date__c, ' 
                        + ' (Select Sale_Price__c, Sale_Date__c From Sales__r ' 
                        + ' where recordTypeId = \'' + RecordTypeManager.saleCompRecordTypeId + '\' order by Sale_Date__c desc NULLS Last limit 1)' 
                        + ' From Property__c m');
        return ans;
  }
  
  global void execute(Database.BatchableContext context, List<SOBject> objects) {   
    for(Property__c p : (List<Property__c>) objects){
        if(p.Sales__r.size() > 0){
            if(p.Last_Sale_Date__C == null || (p.Last_Sale_Date__C <= p.Sales__r[0].Sale_Date__c)){
                 p.Last_Sale_Price__c = p.Sales__r[0].Sale_Price__c;
                 p.Last_Sale_Date__C = p.Sales__r[0].Sale_Date__c;
            }
        }
    }    
    
    update objects;                       
  }

  global void finish(Database.BatchableContext context) {
    
  
  }
  
  @isTest
  private static void testBatch(){
      BatchSalePriceUpdate  con = new BatchSalePriceUpdate();
      con.start(null);
      con.finish(null);
      Property__c property = new Property__c(Property_Address__c = 'alafaya 1');
        insert property;
      con.execute(null,new List<Sobject>{property });
  }
  
  
}